[package]
name = "league_config_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "5.0.1"
iced = { version = "0.12.1" }
rfd = "0.14.1"
serde = "1.0.209"
serde_json = "1.0.127"
